### ISSUE TITLE
See Ya Starbucks - CTA

### ISSUE THREAD

**Issue by mivons** [alexcape/eh-website#19]
If we want to link out to google maps I would like to look at a different text link treatment or possibly having a button in the section

**Comment by alexcape** [comment]
No 3D buttons please, I hate the way they have to be absolutely positioned and fuck with layout. If you want to change the style please consider doing so inline.

**Comment by alexcape** [comment]
**Pushed.** - also the diagonal background in this push.

**Comment by mivons** [comment]
make hover this: #1A9589

**Comment by alexcape** [comment]
**Pushed.**

**Comment by mivons** [comment]
make the link bold and this will be complete

**Comment by alexcape** [comment]
**Staged.**
