### ISSUE TITLE
We're Escape Hatch - Lines

### ISSUE THREAD

**Issue by mivons** [alexcape/eh-website#3]
Can we try and get the headline closer to the lines on both sides. The right is not too bad but would for sure like to get the left side closer to the line.

Also look at the same revision on mobile.

Below is what it should look like or closely resemble:

**Desktop**
![screenshot 2018-02-14 19 29 18](https://user-images.githubusercontent.com/32840979/36235285-967f7f48-11bd-11e8-83bd-04537a76e6b0.png)

**Mobile**
![screenshot 2018-02-14 19 33 33](https://user-images.githubusercontent.com/32840979/36235345-0094695c-11be-11e8-8221-19634c822748.png)

**Comment by alexcape** [comment]
Coming back to this one because there's another way to do it but it requires rebuilding the entire thing >_<

**Comment by mivons** [comment]
Final container width needs to be 1200px

**Comment by alexcape** [comment]
We'll have to talk about this section, I have a few ways of doing this but the bottomline is that either the text has to scale to fill that 600px width and meet the line or the line has to come closer to the text by reducing the width. My alternate solution gives us better control over the line placement but it's pretty hard to control for responsive.

**Comment by alexcape** [comment]
**Pushed.** Think things line up a little better now. Might wanna relook at the tablet breakpoint now that we have a longer statement on the right side.
