### ISSUE TITLE
Turn off HTML5 Video in mobile

### ISSUE THREAD

**Issue by alexcape** [alexcape/eh-website#36]
I found a good fix for turning off that .mp4 video in mobile (apparently display:none; doesn't stop mobile browsers from downloading thus affecting page load performance).

https://stackoverflow.com/questions/28605591/prevent-html5-videos-from-downloading-the-files-on-mobile-videojs

I just need your JS skillz to add this to our scripts file!

**Comment by cawdev** [comment]
This is complete.

**Comment by cawdev** [comment]
I'm reopening this just to stay consistent with the others for now.

**Comment by alexcape** [comment]
This is confirmed working 💯
