### ISSUE TITLE
Gulp tasks

### ISSUE THREAD

**Issue by alexcape** [alexcape/eh-website#37]
I don't know shit about Gulp but I see you used it to minify and clean the css.
Here's a couple more processing things I need your expertise on before I can put this puppy live:

- _autoprefixing_ - I'm using a lot of flexbox, animations, one gradient and one grid, need to probably prefix back like 2 versions on the popular browsers
- _minifying_ - css and js
- _combining?_ - it would be pretty sick to get all of the .css files in one file like we did with the local js files. maybe you know how we could do this without breaking everything?

**Comment by cawdev** [comment]
This is complete.

**Comment by alexcape** [comment]
Perfection
